// source/page/AboutMe.tsx
import React from 'react';
import { Col, Container, Row } from 'react-bootstrap';
import AboutMeTable from '../components/AboutMeTable';

const AboutMe = ({ title, data }) => {
  const { description } = data;

  return (
    <Container className="p-5">
      <Row>
        <h2 className="d-block d-sm-none mb-3">{title}</h2>
      </Row>
      <Row>
        <Col lg={4}>
          <AboutMeTable data={data} />
        </Col>
        <Col lg={7} className="align-self-center">
          {description.split('\n').map((text: string, id: number) => (
            <p key={id} className="d-inline-block rounded-3">
              {text}
            </p>
          ))}
        </Col>
      </Row>
    </Container>
  );
};

export default AboutMe;

// source/components/Svelte/AboutMe.svelte
<script>
  export let about;

  const { nationality, age, birthday, description } = about;
</script>

<div class="col-6">
  <table class="table">
    <tbody>
      <tr>
        <td>{nationality.title}</td>
        <td>{nationality.text}</td>
      </tr>
      <tr>
        <td>{age.title}</td>
        <td>{age.text}</td>
      </tr>
      <tr>
        <td>{birthday.title}</td>
        <td>{birthday.text}</td>
      </tr>
    </tbody>
  </table>
</div>
<div class="col-6 align-self-center">
  {#each description.split('\n') as text}
    <p>{text}</p>
  {/each}
</div>

<style>
  td {
    font-size: 12px;
  }

  p {
    font-size: 12px;
  }
</style>
